coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path("convert/", include("guest_user.urls")),
    path('orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from .views import home, welcome
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   path('', home, name='home'),
   path('welcome/', welcome, name='welcome'),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path
from .views import MyOrderView, CreateOrderProductView

urlpatterns = [
    path('my-order',MyOrderView.as_view(), name='myorder'),
    path('add-product', CreateOrderProductView.as_view(), name='add_order_product')
]

products/urls.py
from .views import ProductListView, ProductFormView
from django.urls import path

urlpatterns = [
    path('allproducts/', ProductListView.as_view(), name='products'),
    path('addproduct/', ProductFormView.as_view(), name='add_product')
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView

urlpatterns = [
   path('login/', LoginView.as_view(template_name='users/login.html'), name='login' ),
   path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
   path('register/', RegisterView.as_view(),  name='register')
]

core/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"order {self.id} by {self.user}"

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    
    def __str__(self):
        return f"{self.order} - {self.product}"

products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    APPETIZER = 'AP'
    MAIN_COURSE = 'MC'
    DESSERT = 'DS'
    BEVERAGE = 'BV'

    CATEGORY_CHOICES = [
        (APPETIZER, 'Appetizer'),
        (BEVERAGE, 'Beverage'),
        (DESSERT, 'Dessert'),
        (MAIN_COURSE, 'Main Course'),
    ]

    name = models.TextField(max_length=100, verbose_name='Name')
    description = models.TextField(max_length=350, verbose_name='Description')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Price')
    available = models.BooleanField(default=True, verbose_name='Available')
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=APPETIZER, verbose_name='Category')
    photo = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name='Photo')

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

orders/forms.py
from django.forms import Form, ModelForm
from .models import OrderProduct

class OrderProductForm(ModelForm):
  class Meta:
    model = OrderProduct
    fields = ['product']

products/forms.py
from .models import Product
from django import forms
class ProductForm(forms.Form):

    APPETIZER = 'AP'
    MAIN_COURSE = 'MC'
    DESSERT = 'DS'
    BEVERAGE = 'BV'

    CATEGORY_CHOICES = [
        (APPETIZER, 'Appetizer'),
        (MAIN_COURSE, 'Main Course'),
        (DESSERT, 'Dessert'),
        (BEVERAGE, 'Beverage'),
    ]

    name = forms.CharField(max_length=100, label='Name')
    description = forms.CharField(max_length=350, label='Description')
    price = forms.DecimalField(max_digits=10, decimal_places=2, label='Price')
    available = forms.BooleanField(initial=True, label='Available', required=False)
    category = forms.ChoiceField(choices=CATEGORY_CHOICES, label='Category')
    photo = forms.ImageField(label='Photo', required=False)
    
    def save(self):
        Product.objects.create(
            name =self.cleaned_data['name'],
            description =self.cleaned_data['description'],
            price = self.cleaned_data['price'],
            available = self.cleaned_data['available'],
            category = self.cleaned_data['category'],
            photo = self.cleaned_data['photo'],
        )
    

core/views.py
from django.shortcuts import redirect, render
from guest_user.decorators import allow_guest_user

# Create your views here.
def home(request):
    return render(request, 'core/home.html')

@allow_guest_user
def welcome(request):
    if request.user.is_authenticated:
        return render(request, 'core/welcome_page.html')
    else:
        return redirect('/')

orders/views.py
from django.views.generic import DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Order
from .forms import OrderProductForm
# Create your views here.

class MyOrderView(LoginRequiredMixin, DetailView):
  model = Order
  template_name = "orders/myorder.html"
  context_object_name = 'order'
  
  def get_object(self, queryset=None ):
    return Order.objects.filter(is_active=True, user=self.request.user).first()

class CreateOrderProductView(LoginRequiredMixin,CreateView):
  template_name = 'order/create_order_product.html'
  form_class = OrderProductForm
  success_url = reverse_lazy('myorder')
  
  def form_valid(self, form):
    order, _ = Order.objects.get_or_create(
      is_active = True,
      user = self.request.user
    )
    form.instance.order = order
    form.instance.quantity = 1
    form.save()
    return super().form_valid(form)

products/views.py
from django.http import HttpResponse
from django.urls import reverse_lazy
from .forms import ProductForm
from .models import Product
from django.views.generic.base import  TemplateView
from django.views import generic
from django.shortcuts import render
# Create your views here.

class ProductListView(generic.ListView):
    model = Product
    template_name = 'products/products_list.html'
    context_object_name = 'products'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Product.CATEGORY_CHOICES
        categorized_products = {category[1]: Product.objects.filter(category=category[0]) for category in categories}
        context['categorized_products'] = categorized_products
        return context

class ProductFormView(generic.FormView):
    template_name = 'products/add_products.html'
    form_class = ProductForm
    success_url= reverse_lazy('products')
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

users/views.py
from django.http import request
from django.contrib.auth.views import LoginView
from .utils import create_guest_user
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy

# Create your views here.
class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("login")

core/templates/core/home.html
{% extends "home.html" %}
{% load static %}
{% load tailwind_filters %}
{% block content %}
    <h1 class="text-4xl md:text-6xl font-bold mb-4">Welcome to our Coffee Shop</h1>
    <p class="text-lg md:text-2xl mb-6 text-center font-mono">
        Satisfy your cravings with our delicious meals <br/>
        and treats.Order online for fast delivery <br/> 
        and fresh ingredients in every bite!
    </p>
    <div class="flex gap-4">
        <a href="{% url 'login' %}" class="px-4 py-2 bg-[#754b32]/30 backdrop-saturate-50 hover:backdrop-saturate-150 text-white font-semibold rounded-lg shadow-md">Login</a>
        <a href="{% url 'welcome' %}" class="px-4 py-2 bg-[#754b32]/30 backdrop-saturate-50 hover:backdrop-saturate-150 text-white font-semibold rounded-lg shadow-md">Guest</a>
    </div>
{% endblock content %}

core/templates/core/welcome_page.html
{% extends "base.html" %}
{% load static %}
{% load tailwind_filters %}
{% block content %}
    
    <h1 class="text-4xl md:text-6xl font-bold mb-4 text-center">Welcome Back</h1>
    
    <div class="px-4 bg-[#754b32]/30 backdrop-saturate-50 rounded-md mx-auto max-w-screen-3xl py-8 sm:px-6 lg:px-8">
    </div>
    <div>
        <iframe style="border-radius:12px" src="https://open.spotify.com/embed/artist/3yKoHgjtyenCOIRaD2Gghu?utm_source=generator&theme=0" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
    </div>
{% endblock content %}

orders/templates/orders/myorder.html
{% extends "base.html" %}
{% block content %}
Mi orden - yey  ☕
{{order.user.username}}
{{order.order_date|date}}

{% for product_order in order.orderproduct_set.all %}
{{product_order.product.name}}
{{product_order.product.price}}
{% endfor %}

{% endblock content %}

products/templates/products/add_products.html
<!doctype html>
<html lang="en">
    <head>
        <title>Add product</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

         <!-- Tailwind -->
         <script src="https://cdn.tailwindcss.com"></script>
    </head>

    <body>
        <header>
            <!-- place navbar here -->
             <h1 class="">Form - Add product</h1>
             
        </header>
        <main>
           <div class="container">
            <form action="{% url "add_product" %}" method='post' enctype="multipart/form-data"> 
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="bg-[#2c2c2a] text-white font-bold py-2 px-4 rounded-full transition hover:scale-105 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50"> 
                    Add
                </button>
            </form>
           </div>
           
        </main>
        <footer>
            <!-- place footer here -->
        </footer>
    </body>
</html>

products/templates/products/products_list.html
{% extends "base.html" %}
{% block content %}
<div class="x-4 bg-white/30 backdrop-saturate-50 rounded-md mx-auto max-w-screen-xl py-8 sm:px-6 lg:px-8  md:w-3/5 p-4 h-96">
    <h1 class="text-4xl md:text-6xl text-[#0e0100] font-bold mb-4 text-center font-mono">Menu</h1>
    <h1 class="text-2xl md:text-4xl text-[#0e0100] font-bold mb-4 text-center font-sans"> ☕</h1>
    <div class="overflow-y-auto h-full">
    <div class="space-y-8">
        {% for category, products in categorized_products.items %}
        <div>
            <h3 class="font-mono text-sm md:text-lg lg:text-xl font-bold bg-[#0e0100] text-[#f5f5f5] inline-block px-2">{{ category }}</h3>
            <span class="p-1 font-bold"><hr class="border-[#0e0100] border-b-2"></span>
            <div class="space-y-4 mt-4">
                {% for product in products %}
                <div class="grid grid-cols-12 items-center gap-4">
                    {% if product.photo %}
                        <div class="col-span-3 md:col-span-2 w-16 h-16 md:w-20 md:h-20">
                            <img src="{{product.photo.url}}" alt="{{product.name}}" class="rounded-full w-full h-full object-cover">
                        </div>
                    {% else %}
                        <div class="col-span-3 md:col-span-2 w-16 h-16 md:w-20 md:h-20">
                            <img src="https://images.unsplash.com/photo-1599481238640-4c1288750d7a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2664&q=80" alt="Ejemplo" class="rounded-full w-full h-full object-cover">
                        </div>
                    {% endif %}
                    <div class="col-span-6 md:col-span-5 flex flex-col pl-4">
                        <h2 class="text-sm md:text-lg lg:text-xl font-sans font-semibold">{{ product.name }}</h2>
                        <p class="text-xs md:text-base lg:text-lg text-[#0e0100]">{{ product.description }}</p>
                    </div>
                    <div class="col-span-3 md:col-span-2 text-sm md:text-lg lg:text-xl text-gray-700">
                        ${{ product.price }}
                    </div>
                    <div class="col-span-12 md:col-span-3 flex justify-start mt-2 md:mt-0">
                        <form action= "{% url "add_order_product" %}" method='post'>
                            {% csrf_token %}
                            <input type='hidden' name='product' value= '{{product.id}}' />
                            <button class="bg-[#0e0100] text-white font-bold py-2 px-4 rounded-full transition hover:scale-105 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50">
                                Add
                            </button>
                        </form>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Coffe Shop</title>
    <meta charset="utf-8" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Tailwind -->
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <div class="relative w-screen h-screen overflow-hidden">
        <img class="w-full h-full object-cover" src="{% static 'core/images/welcome-to-coffee-shop.jpg' %}" alt="Coffee Shop" />
        <div class="absolute inset-0 flex flex-col items-center justify-center text-white bg-black bg-opacity-50">
            <div>
                <div class="sm:hidden">
                  <label for="Tab" class="sr-only">Tab</label>
                  <select id="Tab" class="w-full rounded-md border-gray-200">
                    <option>Menu</option>
                    <option>Checkout</option>
                    <option select>Log out</option>
                  </select>
                </div>
              
                <div class="hidden sm:block">
                  <div class="">
                    <nav class="-mb-px flex gap-6" aria-label="Tabs">
                      <a
                        href="{% url "products" %}"
                        class=" inline-block rounded-full border border-2 border-[#0e0100] bg-[#754b32] p-3 text-[#0e0100] hover:bg-white/20 hover:text-[#0e0100] focus:outline-none active:text-white"
                      >
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16c0 1.1.9 2 2 2h12a2 2 0 0 0 2-2V8l-6-6z"/><path d="M14 3v5h5M16 13H8M16 17H8M10 9H8"/></svg>
                      </a>
              
                      <a
                        href="#"
                        class=" inline-block rounded-full border border-2 border-[#0e0100] bg-[#754b32] p-3 text-[#0e0100] hover:bg-white/20 hover:text-[#0e0100] focus:outline-none active:text-white"
                      >
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="M7 15h0M2 9.5h20"/></svg>
                      </a>
                      <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="inline-block rounded-full border border-2 border-[#0e0100] bg-[#754b32] p-3 text-[#0e0100] hover:bg-white/20 hover:text-[#0e0100] focus:outline-none  active:text-white">
                          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                            <path d="M10 3H6a2 2 0 0 0-2 2v14c0 1.1.9 2 2 2h4M16 17l5-5-5-5M19.8 12H9"/>
                          </svg>
                        </button>
                      </form>
                    </nav>
                  </div>
                </div>
              </div>
            {% block content %}{% endblock content %}
        </div>
    </div>
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Coffe Shop</title>
    <meta charset="utf-8" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Tailwind -->
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <div class="relative w-screen h-screen overflow-hidden">
        <img class="w-full h-full object-cover" src="{% static 'core/images/coffee-shop.jpg' %}" alt="Coffee Shop" />
        <div class="absolute inset-0 flex flex-col items-center justify-center text-white bg-black bg-opacity-50">
            {% block content %}{% endblock content %}
        </div>
    </div>
</body>
</html>

users/templates/users/login.html
{% extends "home.html" %}
{% load static %}
{% load tailwind_filters %}
{% block content %}
    <h1 class="text-4xl md:text-6xl font-bold mb-4 text-center">Welcome to our Coffee Shop</h1>
    <div class="px-4 bg-[#754b32]/30 backdrop-saturate-50 rounded-md mx-auto max-w-screen-xl py-8 sm:px-6 lg:px-8">
        <div class="flex ">
            <a
                class=" inline-block rounded-full border border-2 border-[#0e0100] bg-[#754b32] p-3 text-[#0e0100] hover:bg-white/20 hover:text-[#0e0100] focus:outline-none  active:text-white"
                href="{% url 'home' %}"
            >
            <span class="sr-only"> Back </span>

            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M19 12H6M12 5l-7 7 7 7"/></svg>
            </a>

        </div>
        <form action="" method="post" class="mx-auto mb-0 mt-4 max-w-xl space-y-6">
            {% csrf_token %}
            <div>
                <div class="mb-6">
                    <label for="id_username" class="sr-only">Username</label>
                    <div class="relative">
                        <input
                            type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username"
                            class="w-full rounded-lg text-white p-4 pe-12 text-sm shadow-sm bg-[#754b32]/50 border border-2 border-[#0e0100] placeholder-white active:border-[#0e0100] focus:outline-none"
                            placeholder="Enter email"
                        />
                        <span class="absolute inset-y-0 end-0 grid place-content-center px-4">
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                class="h-5 w-5 text-white"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                            >
                                <path
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"
                                    d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207"
                                />
                            </svg>
                        </span>
                    </div>
                </div>
                <div class="mb-6">
                    <label for="id_password" class="sr-only">Password</label>
                    <div class="relative">
                        <input
                            type="password" name="password" autocomplete="current-password" required="" id="id_password"
                            class="w-full rounded-lg p-4 pe-12 text-sm shadow-sm bg-[#754b32]/50 border border-2 border-[#0e0100] placeholder-white focus:outline-none"
                            placeholder="Enter password"
                        />
                        <span class="absolute inset-y-0 end-0 grid place-content-center px-4">
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                class="h-5 w-5 text-white"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                            >
                                <path
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"
                                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                                />
                                <path
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"
                                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
                                />
                            </svg>
                        </span>
                    </div>
                </div>
            </div>
            <div class="flex flex-col items-center justify-between">
                <button
                    type="submit"
                    class="px-4 py-2 bg-[#754b32]  text-white font-semibold rounded-lg shadow-md  hover:bg-white/20"
                >
                    <span class="inline-flex items-center">
                        Sign in
                    </span>
                </button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "home.html" %}
{% load tailwind_filters %}
{% block content %}
<div class="container mx-auto w-1/3">
    <h1 class="text-4xl md:text-6xl font-bold mb-4 text-center">Welcome to our Coffee Shop</h1>
    <form action="" method="post" class="my-8">
        {% csrf_token %}
        <div>
            <div class="mb-6">
                <label for="id_username" class="sr-only">Username</label>
                <div class="relative">
                    <input
                        type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username"
                        class="w-full rounded-lg text-white p-4 pe-12 text-sm shadow-sm bg-[#754b32]/50 border border-2 border-[#0e0100] placeholder-white active:border-[#0e0100] focus:outline-none"
                        placeholder="Enter email"
                    />
                    <span class="absolute inset-y-0 end-0 grid place-content-center px-4">
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            class="h-5 w-5 text-white"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                        >
                            <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207"
                            />
                        </svg>
                    </span>
                </div>
                <span class=" font-mono text-sm helptext" id="id_username_helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
            </div>
            <div class="mb-6">
                <label for="id_password1" class="sr-only">Password</label>
                <div class="relative">
                    <input
                        type="password" name="password1" autocomplete="new-password" required id="id_password1"
                        class="w-full rounded-lg p-4 pe-12 text-sm shadow-sm bg-[#754b32]/50 border border-2 border-[#0e0100] placeholder-white focus:outline-none"
                        placeholder="Enter password"
                    />
                    <span class="absolute inset-y-0 end-0 grid place-content-center px-4">
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            class="h-5 w-5 text-white"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                        >
                            <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                            />
                            <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
                            />
                        </svg>
                    </span>
                </div>
            </div>
            <div class="mb-6">
                <label for="id_password2" class="sr-only">Password</label>
                <div class="relative">
                    <input
                        type="password" name="password2" autocomplete="new-password" required= id="id_password2"
                        class="w-full rounded-lg p-4 pe-12 text-sm shadow-sm bg-[#754b32]/50 border border-2 border-[#0e0100] placeholder-white focus:outline-none"
                        placeholder="Enter password"
                    />
                    <span class="absolute inset-y-0 end-0 grid place-content-center px-4">
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            class="h-5 w-5 text-white"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                        >
                            <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                            />
                            <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
                            />
                        </svg>
                    </span>
                </div>
            </div>
        </div>
        <div class="flex flex-col items-center justify-between">
            <button
                type="submit"
                class="px-4 py-2 bg-[#754b32]  text-white font-semibold rounded-lg shadow-md  hover:bg-white/20"
            >
                <span class="inline-flex items-center">
                    Sign up
                </span>
            </button>
        </div>
    </form>
    <p class="text-center text-sm text-gray-500 mt-4">
        Already have an account?
        <a class="underline" href="{% url "login" %}">Log in</a>
    </p>
</div>
{% endblock content %}